source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

# Database
gem 'pg'

# Dev Server
gem 'puma', '~> 3.0'

# Serialization
gem 'active_model_serializers', '~> 0.10.0'

# Record filtering and searching
gem 'ransack'

# Preprocessors
gem 'haml'
gem 'sass-rails', '>= 3.2'

# JQuery
gem 'jquery-rails'

# Bootstrap
gem 'bootstrap-sass', '~> 3.3.6'

# Static pagination
gem 'will_paginate', '~> 3.1.0'
gem 'will_paginate-bootstrap'

# Decorator
gem 'drape', '~> 1.0.0.beta1'

group :development, :test do
  gem 'byebug', platform: :mri

  # Mock objects factory
  gem 'factory_girl_rails'

  # Fake data provider
  gem 'faker'

  # Ruby linter
  gem 'rubocop'

  # Rspec linter
  gem 'rubocop-rspec'

  # N+1 query detection
  gem 'bullet'

  # Detect rails code smells
  gem 'reek'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Test coverage
  gem 'simplecov', require: false

  # Testing framework
  gem 'rspec-rails', '~> 3.5'

  # Matcher helpers
  gem 'shoulda-matchers', require: false
  gem 'json_matchers'

  # Database cleaning between test
  gem 'database_cleaner'

  # Webdriver
  gem 'capybara'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
