source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'

# Database
gem 'pg'

# Dev Server
gem 'puma', '~> 3.0'

# Serialization
gem 'active_model_serializers', '~> 0.10.0'

group :development, :test do
  gem 'byebug', platform: :mri

  # Mock objects factory
  gem 'factory_girl_rails'

  # Fake data provider
  gem 'faker'

  # Ruby linter
  gem 'rubocop'
end

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Test coverage
  gem 'simplecov', require: false

  # Testing framework
  gem 'rspec-rails', '~> 3.5'

  # Matcher helpers
  gem 'shoulda-matchers', require: false

  # Database cleaning between test
  gem 'database_cleaner'

  # Webdriver
  gem 'capybara'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
